name: Build and Test Trivia App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [20]

    steps:
        - uses: actions/checkout@v4
        - name: Use Node.js ${{ matrix.version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.version }}
        - name: npm ci, build and test
          run: |
            npm ci
            npm run build --if-present
            npm test      
